---
title: "esm 206 lab 10"
author: "Virginia Pan"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install packages
library(beepr)
library(praise)
library(cowsay)
library(paletteer)
library(sf)
library(tidyverse)
library(here)
library(janitor)
```

## beepr beeps

Use `beep()` to make an audio alert when your code is done running 

```{r, eval=FALSE}
for(i in rev(seq(1:999))) {
  print(paste(i, "bottels of beer on the wall"))
}

beep(4)
```

## praise and cowsay - kind and fun

```{r}
praise("${Exclamation}, ${EXCLAMATION}...${exclamation}!!!!")


praise("Holy ${creating}, Batmand - this code is ${ADJECTIVE}")
```

## Use cowasy::say to make a character say something to you

## retroactively use github with a project
In councel: 
usethis::use_git()
usethis::use_github()

## use paletteer to access thousands of color palettes 

```{r}
storms %>% 
  group_by(name) %>% 
  summarize(min_pressure = min(pressure, na.rm = TRUE)) %>% 
  slice_min(n = 10, min_pressure) %>% 
  ggplot(aes(x = min_pressure, y = name)) +
  geom_col(aes(fill = name)) +
  scale_fill_paletteer_d("palettetown::ivysaur")
```


## one spatial data example 

```{r}
vegatation <- read_sf(here("data", "doc.kml")) %>% 
  select(Name) %>% 
  clean_names()

## create a map w/ theme_minimal, color change based on vegetation, color of line to NA
ggplot(data = vegatation) +
  geom_sf(aes(fill = name), color = "NA") +
  theme_minimal() +
  scale_fill_paletteer_d("ggthemes::manyeys") +
  labs(title = "Jornada Basin LTER Vegetation",
       caption = "Source: Jornada LTER")
  
## create an image
ggsave(filename = "my_awsome_map.jpg", width = 8, height = 5) #default apply to last plot run; default saves to root of where project is OR use here

```


